---
- apt:
    pkg: unzip
    state: latest

- get_url:
    url: "https://dl.bintray.com/mitchellh/consul/{{ consul_archive }}"
    dest: "/tmp/{{ consul_archive }}"

- unarchive:
    src: "/tmp/{{ consul_archive }}"
    dest: /opt/consul/bin
    copy: no

- file:
    state: link
    src: /opt/consul/bin/consul
    dest: /usr/local/bin
    force: yes

- get_url:
    url: "https://dl.bintray.com/mitchellh/consul/{{ consul_ui_archive }}"
    dest: "/tmp/{{ consul_ui_archive }}"

- unarchive:
    src: "/tmp/{{ consul_ui_archive }}"
    dest: /opt/consul/ui
    copy: no
